build:
	cc Main.c -o Signal
run:	
	./Signal
help:
	
	@echo Use : \<make build\> to build project	
	@echo Use : \<make help\> for help
	@echo Use : \<make run\> to execute process1
	@echo Use : \<make clean\> remove executable

clean:
	rm Sender
	rm Receiver
