buid:
	cc Main.c -o Equal

run:
	./Equal ${ARGS}

help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make ARGS=\"Source_filename Destination_filename\" run\> to execute project  
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> remove executable
	
clean:
	rm Equal
