build:
	cc Main.c -o UnnamedPipe
run:
	./UnnamedPipe

help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make run\> to execute project  
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> remove executable
	
clean:
	rm UnnamedPipe
