build:
	cc Main.c -o OpenMode
	
help:
	@echo Use : make ARGS1 = \"filename\" ARGS2 = \"Mode\" run to execute.
	@echo Use : make clean to remove executable file.
	@echo Use : read,write,read-write,append as modes

run:
	./OpenMode ${ARGS1} ${ARGS2}
	
clean:
	rm OpenMode
	
