build:
	cc Main.c -o Hole

run:
	./Hole ${ARGS}

help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make ARGS=\"Filename\" run\> to execute project  
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> remove executable
	
clean:
	rm Hole
