build:
	cc Main.c -o Redirect

help:
	@echo Use : \< make build\> for build the project.
	@echo Use : ./Readirect \< filename\(input\) \> filename\(output\) to run
	@echo Use : \< make help\> for help
	@echo Use : \<make clean\> to remove executable
	@echo Use : \>\/\<\/\>\> as Operator
	
clean:
	rm Redirect
