buid:
	cc Main.c -o Move

run:
	./Move ${ARGS1} ${ARGS2} 

help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make ARGS1=\"source_directory\" ARGS2=\"destination_directory\" run \> to execute project  
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> remove executable
	
clean:
	rm Move
