build:
	cc Thread.c -o Thread -l pthread
run:
	./Thread

help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make run\> to execute project  
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> remove executable
	
clean:
	rm Thread
