build:
	cc Main.c -o myexe
	cc Rename.c -o Rename

run:
	./myexe ${ARGS}

help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make ARGS=\"Directory_name\" run\> to execute project  
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> remove executable
	
clean:
	rm myexe
	rm Rename
