build:
	cc Main.c -o ReadAll
	
help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make help\> for help
	@echo Use : \<make ARGS=\"filename\"\> to execute the project
	@echo Use : \<make clean\> to remove executable
	
run:
	./ReadAll ${ARGS}
	
clean:
	rm ReadAll
