build:
	cc Main.c -o SharedMem
	cc Process1.c -o Process1
	cc Process2.c -o Process2
run:
	./SharedMem

help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make run\> to execute project  
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> remove executable
	
clean:
	rm SharedMem
	rm Process1
	rm Process2
