build:
	cc Receiver.c -o Receiver
	cc Sender.c -o Sender
run:	
	./Receiver
help:
	
	@echo Use : \<make build\> to build project	
	@echo Use : \<make help\> for help
	@echo Use : \<make run\> to execute project
	@echo Use : \<make clean\> remove executable

clean:
	rm Sender
	rm Receiver
