build:
	cc Main.c -o Info

run:
	./Info ${ARGS}
	
help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make ARGS=\"filename\" run\> to run
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> to remove executable

clean:
	rm Info
