buid:
	cc Main.c -o Copy

run:
	./Copy ${ARGS1} ${ARGS2} 

help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make ARGS1=\"filename\" ARGS2=\"filename\" run \> to execute project  
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> remove executable
	
clean:
	rm Copy
