buid:
	cc Main.c -o Info

run:
	./Info ${ARGS}

help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make ARGS=\"directory_name filename\" run\> to execute project  
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> remove executable
	
clean:
	rm Info
