build:
	cc Main.c -o ReadBytes
	
help:
	@echo Use : \<make ARGS1 = \"filename\" ARGS2 = \"No_of_bytes\" run\> to execute.
	@echo Use : \<make clean\> to remove executable file.
	@echo Use : \<make build\> to build the project

run:
	./ReadBytes ${ARGS1} ${ARGS2}
	
clean:
	rm ReadBytes
	
