buid:
	cc Main.c -o Remove

run:
	./Remove ${ARGS1}

help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make ARGS1=\"directory_name\" run\> to execute project  
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> remove executable
	
clean:
	rm Remove
