buid:
	cc Main.c -o Details

run:
	./Details ${ARGS} 

help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make ARGS=\"Directory_name\"\> to execute project  
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> remove executable
	
clean:
	rm Details
