build:
	cc Main.c -o Create
	cc Process2.c -o Process2
	cc Process3.c -o Process3
	cc Process4.c -o Process4
run:
	./Create

help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make run\> to execute project  
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> remove executable
	
clean:
	rm Create
	rm Process2
	rm Process3
	rm Process4
