build:
	cc Main.c -o ChkAccess
	
help:
	@echo Use : make ARGS1 = \"filename\" ARGS2 = \"Mode\" run to execute.
	@echo Use : make clean to remove executable file.
	@echo Use : read,write,execute as modes

run:
	./ChkAccess ${ARGS1} ${ARGS2}
	
clean:
	rm ChkAccess
	
