build:
	cc Process1.c -o Sender
	cc Process2.c -o Receiver
Send:	
	./Sender
Receive:
	./Receiver
help:
	
	@echo Use : \<make build\> to build project	
	@echo Use : \<make help\> for help
	@echo Use : \<make Send\> to execute process1
	@echo Use : \<make Receive\> to execute process2
	@echo Use : \<make clean\> remove executable

clean:
	rm Sender
	rm Receiver
