build:
	cc Main.c -o Write
	cc File.c -o file

run:
	./Write

help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make run\> to execute project  
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> remove executable
	
clean:
	rm Write
	rm file
