buid:
	cc Main.c -o Search

run:
	./Search ${ARGS} 

help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make ARGS1=\"directory_name file_name\" run \> to execute project  
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> remove executable
	
clean:
	rm Search
