build:
	cc Main.c -o Create

run:
	./Create ${ARGS}

help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make ARGS=\"Directoryname  Filename\" run\> to execute project  
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> remove executable
	
clean:
	rm Create
