build:
	cc Main.c -o Write
	
help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make ARGS=\"filename\"\> to execute project
	@echo Use : \<make clean\> to remove executable
	@echo Use : \<make help\> for help
	
run:
	./Write ${ARGS}
	
clean:
	rm Write
	
