build:
	cc Main.c -o myexe
	cc Count.c -o Count

run:
	./myexe

help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make run\> to execute project  
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> remove executable
	
clean:
	rm myexe
	rm Count
