build:
	cc Main.c -o Level3
	cc Process1.c -o Process1
	cc Process2.c -o Process2
	cc Process3.c -o Process3

run:
	./Level3

help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make run\> to execute project  
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> remove executable
	
clean:
	rm Level3
	rm Process1
	rm Process2
	rm Process3
