build:
	cc Process1.c -o P1
	cc Process2.c -o P2
run1:	
	./P1
run2:
	./P2
help:
	
	@echo Use : \<make build\> to build project	
	@echo Use : \<make help\> for help
	@echo Use : \<make run P1\> to execute process1
	@echo Use : \<make run P2\> to execute process2
	@echo Use : \<make clean\> remove executable
	
clean:
	rm P1
	rm P2
